[package]
name = "crust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sum"
path = "src/c_lib.rs"
crate-type = ["staticlib"]

[profile.release]
opt-level = 3

[dependencies]
dirs = "3.0.2"